<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\PdfService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PdfController extends Controller
{
    public function __construct(
        private PdfService $pdfService
    ) {}

    public function generate(Request $request): Response
    {
        $validated = $request->validate([
            'content' => 'required|string',
            'filename' => 'nullable|string|max:255',
            'download' => 'nullable|boolean',
        ]);

        return $this->pdfService->generatePdf($validated['content'], [
            'filename' => $validated['filename'] ?? 'document.pdf',
            'download' => $validated['download'] ?? true,
        ]);
    }

    public function test(): Response
    {
        $testContent = <<<'HTML'
<h1>PDF Test Document</h1>
<p>This is a test PDF generated by the PdfService.</p>
<p><strong>Specifications:</strong></p>
<ul>
    <li>Dimensions: 240mm × 90mm</li>
    <li>Orientation: Landscape</li>
    <li>Generated at: {date}</li>
</ul>
<p>This PDF demonstrates the service is working correctly with the specified dimensions.</p>
HTML;

        $testContent = str_replace('{date}', now()->format('Y-m-d H:i:s'), $testContent);

        return $this->pdfService->generatePdf($testContent, [
            'filename' => 'test-pdf-240x90mm',
            'download' => false, // Stream instead of download for testing
        ]);
    }
}
